scene.SetBackground(gfx.Color(0.1, 0.1, 0.1))
eh=io.LoadPDB("./examples/demos/data/7rut.pdb")
sdh_go=gfx.Entity("SDH", eh)
scene.Add(sdh_go)
scene.CenterOn(sdh_go)
sdh_go.SetRenderMode(gfx.RenderMode.HSC)
sdh_go.SetColor(gfx.Color(0.5, 0.5, 0.5), '')
sdh_go.SetColor(gfx.Color(0,1,0),"rtype=H")
sdh_go.SetDetailColor(gfx.Color(0.7,1.0,0.8),"rtype=H")
sdh_go.SetColor(gfx.Color(1,0,0),"rtype=E")
sdh_go.SetDetailColor(gfx.Color(1.0,0.8,0.2),"rtype=E")

